server:
  port: ${SERVER_PORT:8191}

spring:
  application:
    name: ${APPLICATION_NAME:ILP Server}

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  flyway:
    enabled: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgresPlusDialect
    show-sql: true

  # Required for jsonb type
  datasource:
    hikari:
      maximumPoolSize: ${DATASOURCE_MAX_POOL_SIZE:20}
      data-source-properties:
        stringtype: unspecified
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/ilp}
    username: ${DATASOURCE_USERNAME:ilpuser}
    password: ${DATASOURCE_PASSWORD:ilpuser}


