server:
  port: ${SERVER_PORT:8191}

spring:
  application:
    name: ${APPLICATION_NAME:ILP Server}

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  flyway:
    enabled: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgresPlusDialect
      jakarta:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: none
              create-target: ilp-create.sql
    show-sql: true

  # Required for jsonb type
  datasource:
    hikari:
      maximumPoolSize: ${DATASOURCE_MAX_POOL_SIZE:20}
      data-source-properties:
        stringtype: unspecified
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5436/ilp}
    username: ${DATASOURCE_USERNAME:ilpuser}
    password: ${DATASOURCE_PASSWORD:ilpuser}
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 64KB
      max-file-size: 5MB
      max-request-size: 50MB

logging:
  file:
    path: logs

jwt:
  secret: Ilp-secret-value
  tokenDuration: PT12H
  refreshDuration: P15D

application:
  root-store-path: store
