version: "3"

services:
  ilp-server:
    build: .
    image: ilp-server
    container_name: ilp-server
    expose:
      - 8191
    ports:
      - 8191:8191
    env_file:
      - app.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
